/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;  

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ITALO
 */
public class bostinha2 extends javax.swing.JFrame {
    int pc=0,vc=0;
    /**
     * Creates new form bostinha2
     */
    public bostinha2() {
         this.setLocationRelativeTo(null);
        setResizable(false);
        initComponents();  
         jComboItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","PEDRA", "PAPEL", "TESOURA"}));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboItem = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        jLabelResultRandom = new javax.swing.JLabel();
        jLabelResultPc = new javax.swing.JLabel();
        jLabelResultUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboItemActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 255));
        jButton1.setText("JOGAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha entre Pedra, Papel e Tesoura");

        jLabelResult.setFont(new java.awt.Font("Segoe UI Semibold", 3, 14)); // NOI18N
        jLabelResult.setText("Resultado:");

        jLabelResultRandom.setFont(new java.awt.Font("Franklin Gothic Book", 1, 24)); // NOI18N
        jLabelResultRandom.setForeground(new java.awt.Color(255, 102, 0));
        jLabelResultRandom.setText("     ...");

        jLabelResultPc.setBorder(javax.swing.BorderFactory.createTitledBorder("Comp"));

        jLabelResultUser.setBorder(javax.swing.BorderFactory.createTitledBorder("Vc"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelResultUser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jComboItem, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelResultRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabelResult)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelResultPc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelResultPc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelResultUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelResultRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jLabelResult))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Random gerador = new Random();

        int x = gerador.nextInt(3);  // 0 pedra
                                     // 1 papel
                                     // 2 tesoura
                                    
                                     
                                     
        if(jComboItem.getSelectedItem().equals("PEDRA")){
           if(x == 0){
               jLabelResultRandom.setText("PEDRA");
               jLabelResult.setText("EMPATE");
           }
           else if(x == 1){
                jLabelResultRandom.setText("PAPEL");
               jLabelResult.setText("VOCÊ FOI DERROTADO!");
               pc+=1;
           }
           else {
                jLabelResultRandom.setText("TESOURA");
              jLabelResult.setText("VOCÊ VENCEU !!!");
              vc+=1;
           }
           jLabelResultPc.setText(""+pc);
           jLabelResultUser.setText(""+vc);
       }
        
        
        else if(jComboItem.getSelectedItem().equals("PAPEL")){
            if(x == 0){
                 jLabelResultRandom.setText("PEDRA");
                jLabelResult.setText("VOCÊ VENCEU !!!");
                vc+=1;
            }
            else if( x == 1){
                 jLabelResultRandom.setText("PAPEL");
                jLabelResult.setText("EMPATE");
            }
            else {
                 jLabelResultRandom.setText("TESOURA");
                jLabelResult.setText("VOCÊ PERDEU );");
                pc+=1;
            }
           jLabelResultPc.setText(""+pc);
           jLabelResultUser.setText(""+vc);
        }
        
        
        else if(jComboItem.getSelectedItem().equals("TESOURA")){
            if (x == 0){
                jLabelResultRandom.setText("PEDRA");
                jLabelResult.setText("VOCÊ PERDEU");
                pc+=1;
            }
            if(x == 1){
                jLabelResultRandom.setText("PAPEL");
                jLabelResult.setText("VITORIA!!");
                vc+=1;
            }
            else {
                jLabelResultRandom.setText("TESOURA");
                jLabelResult.setText("EMPATE");
            }
           jLabelResultPc.setText(""+pc);
           jLabelResultUser.setText(""+vc);
        }
        else if(jComboItem.getSelectedItem().equals(" ")){
            JOptionPane.showMessageDialog(null,"Você deve escolher um objeto para jogar","ERROR!",JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboItemActionPerformed
        jLabelResultRandom.setText("     ...     ");
        jLabelResult.setText("RESULTADO");
    }//GEN-LAST:event_jComboItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bostinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bostinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bostinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bostinha2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bostinha2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelResultPc;
    private javax.swing.JLabel jLabelResultRandom;
    private javax.swing.JLabel jLabelResultUser;
    // End of variables declaration//GEN-END:variables
}
